### PR TITLE
Fix broken src/bin link

### PR DESCRIPTION
**Pull request by jvasile**
I believe the `bin` file in the top-level should be a symbolic link to src/bin.  This patch just replaces that text file with a proper link.

### CODE REVIEW

**Comment by HMarzban** [comment]
@jvasile, Thanks for PR, It's true, It should be a symbolic link to `src/bin`.
I wonder, we have this symbolic link already! [`./bin`](https://github.com/nwspk/docs.plus/blob/master/bin)
Would you help me and give me more info to find the problem you found?

**Comment by jvasile** [comment]
On a fresh checkout  of the repo, `./bin` does not appear to be a link.  It appears to be a text file containing "src/bin".

```
$ git clone https://github.com/nwspk/docs.plus.git
Cloning into 'docs.plus'...
remote: Enumerating objects: 42520, done.
remote: Counting objects: 100% (1036/1036), done.
remote: Compressing objects: 100% (488/488), done.
remote: Total 42520 (delta 467), reused 1021 (delta 456), pack-reused 41484
Receiving objects: 100% (42520/42520), 19.56 MiB | 20.57 MiB/s, done.
Resolving deltas: 100% (29919/29919), done.
$ cd docs.plus
$ ls -al bin
-rw-r--r-- 1 james james 7 May  9 09:46 bin
$ cat bin
src/bin%
$ cd bin
cd: not a directory: bin  
```

**Comment by edsaperia** [comment]
Hi @jvasile, thanks for your interest in our project!
I'm very curious, how did you find it, and what are you thinking of using it for?

**Comment by jvasile** [comment]
@edsaperia Hi I'm working with the https://permanent.org team on https://community.webmonetization.org/storagetothepeople and we're making a web-monetized etherpad storage backend.  The GFTW team mentioned docs.plus to us, so I figured I'd check out the codebase.

**Pull request merged**
